//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPermanencia.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_Nota_Asistencia
    {
        public Nullable<int> Id_Alumno { get; set; }
        public Nullable<int> Id_Asignatura { get; set; }
        public int Id_Semestre { get; set; }
        public Nullable<int> Id_Medición { get; set; }
        public Nullable<double> F_Asistencia { get; set; }
        public Nullable<int> F_Notas_Curso { get; set; }
        public Nullable<int> F_Notas_Rendidas { get; set; }
        public Nullable<int> F_Notas_Azules { get; set; }
        public Nullable<double> F_Promedio { get; set; }
    }
}
