//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPermanencia.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Full_Alumnos
    {
        public int Id_Alumno { get; set; }
        public Nullable<int> Id_Asignatura { get; set; }
        public Nullable<int> Id_Medición { get; set; }
        public Nullable<int> Monto_Deuda { get; set; }
        public Nullable<int> Cant_Deuda { get; set; }
        public int Asig_Azules { get; set; }
        public int Asistencias { get; set; }
    }
}
