//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPermanencia.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_Alumno
    {
        public int Id_Alumno { get; set; }
        public Nullable<int> Id_Sede { get; set; }
        public Nullable<double> Id_Carrera { get; set; }
        public string Desc_Alumno { get; set; }
        public string Desc_Rut_Alumno { get; set; }
        public string Id_Jornada { get; set; }
    }
}
