//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPermanencia.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_Asignatura
    {
        public int Id_Asignatura { get; set; }
        public string Cod_Asignatura { get; set; }
        public Nullable<int> Seccion { get; set; }
        public string Desc_Asignatura { get; set; }
        public Nullable<int> Id_Carrera { get; set; }
        public Nullable<int> Id_Profesor { get; set; }
        public string Id_Jornada { get; set; }
    }
}
