//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPermanencia.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_Mes_Deuda
    {
        public int Id_Mes_Deuda { get; set; }
        public string Desc_Mes_Deuda { get; set; }
        public Nullable<int> Id_Año_Deuda { get; set; }
    }
}
